services:
  nginx:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ~/.ssl/privkey.pem:/etc/nginx/site_certs/privkey.pem
      - ~/.ssl/fullchain.pem:/etc/nginx/site_certs/fullchain.pem
    ports:
      - 443:443
      - 80:80
    networks:
      - nginx-reverse-proxy
    links:
      - hello-world:hello-world.test.drew
      - hello-world2:hello-world2.test.drew
    
  hello-world:
    image: nginxdemos/hello
    networks:
      - nginx-reverse-proxy

  hello-world2:
    image: nginxdemos/hello
    networks:
      - nginx-reverse-proxy
  
networks:
  nginx-reverse-proxy:
    driver: bridge